platform :ios, '8.0'
use_frameworks!

pod 'Charts'
pod 'MMSpreadsheetView', :git => 'https://github.com/EmperorLeo/MMSpreadsheetView.git'
pod 'CMPopTipView', :git => 'https://github.com/EmperorLeo/CMPopTipView.git'
pod 'FBSDKCoreKit'
pod 'FBSDKLoginKit'
pod 'FBSDKShareKit'
pod 'Alamofire', '~> 3.0'
pod 'mopub-ios-sdk'
pod 'Fabric'
pod 'TwitterKit'
pod 'TwitterCore'